### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by diondokter**
Updated the nb crate to the 1.0.0 release.
Updated the patch level for other crates as well (this has no effect for the crate though).

### CODE REVIEW

**Comment by hannobraun** [comment]
Thank you, looks good to me!

**Comment by jonas-schievink** [comment]
This duplicates the nb crate since embedded-hal depends on an older version of it

**Comment by hannobraun** [comment]
Isn't `nb` 1.0 brought in through the semver trick anyway?

**Comment by jonas-schievink** [comment]
Ah, right. I forgot we did that.

**Comment by nebelgrau77** [comment]
I just stumbled upon a problem that seems to be related to this. I'm using the master branch, and here's what happens:

Bottomline: nrf-hal-common won't compile. The reason is this:

```rust
 = note: expected fn pointer `fn(&mut saadc::Saadc, &mut PIN) -> core::result::Result<_, nb::Error<()>>` (enum `nb::Error`)
               found fn pointer `fn(&mut saadc::Saadc, &mut PIN) -> core::result::Result<_, nb::Error<()>>` (enum `nb::Error`)
 = note: perhaps two different versions of crate `nb` are being used?
```

This affects `saadc` and `timer` modules. 
In two cases the "expected" and "found" look identical as seen above, but then they aren't:

```rust
    = note: expected enum `nb::Error<void::Void>`
               found enum `nb::Error<_>`
    = note: perhaps two different versions of crate `nb` are being used?
```

If I run `cargo tree` it does confirm that two different versions of nb are used: v1.0.0 in the nrf-common-hal, and v0.1.2 in embedded-hal. 

So I checked something that works for me: https://github.com/nebelgrau77/ItsyBitsy_nRF52840_ADC_serialTX - this uses the v0.11.0 of the nrf-common-hal, pulled from crates.io, so the nb version was still v0.1.2. 

In fact downgrading it back to 0.1.2 in a local fork of the master fixed it. 

There's a big fat chance I'm missing something, though! :)

**Comment by hannobraun** [comment]
Please try running `cargo update` instead. That should pick up nb 0.1.3, which provides full compatibility with 1.0 using the semver trick.

**Pull request merged**
