### PR TITLE
readme: add Getting Started

### PR DESCRIPTION
**Pull request by MarcinSzymczyk**
Short description of required software and building blinky.
Based on @Istar-Eldritch post in #60

### CODE REVIEW

**Comment by hannobraun** [comment]
I tend to agree. The way described here is also not what I've seen from most other Rust-specific documentation (which tends to use OpenOCD). I've never even heard of (let alone used) the nRF Command Line Tools before :-)

I think ideally, we'd link to the embedded Rust book in the README, and add an explanation of which specifics differ. That said, this pull request is better than nothing (which pretty much is what we have right now), so unless @MarcinSzymczyk is willing to make more changes, I'd be ready to merge this as-is.

**Comment by therealprof** [comment]
Works for me.

**Comment by MarcinSzymczyk** [comment]
@hannobraun I have described the way that would be (at least from my experience) easiest for people who code on nRF52 in C and want to try Rust.

I will take a look at the embedded book (is it [this one](https://docs.rust-embedded.org/book/intro/index.html) or [this one](https://docs.rust-embedded.org/discovery/index.html)?) and come up with something.

**Comment by hannobraun** [comment]
@MarcinSzymczyk Thank you. I'd guess they're probably both worth linking to, although I think [The Embedded Rust Book](https://docs.rust-embedded.org/book/intro/index.html) is probably more relevant overall.

**Comment by jamesmunns** [comment]
Hey @MarcinSzymczyk, are you still planning on working on this?

**Comment by Istar-Eldritch** [comment]
From the previous discussion its not clear if this should go to the README or somewhere else. Maybe the way to go is to link the [tooling section of the Rust embedded book](https://docs.rust-embedded.org/book/intro/tooling.html) and clarify differences or specificness of the nrf52 family?

@jamesmunns & @MarcinSzymczyk if you are busy I'm happy to take the initiative and have a go at documenting this. Its a while and I have an upcoming project on the nrf52 so I'll be happy to document how I do my setup using OpenOCD.

**Comment by MarcinSzymczyk** [comment]
Hi all, sorry for the delay.
@Istar-Eldritch sure, go ahead. Closing this PR.

**Pull request closed without merging**
