### PR TITLE
Make error enums #[non_exhaustive]

### LINKED ISSUE #257: Mark error enums as `#[non_exhaustive]`
This makes adding more variants non-breaking

### PR DESCRIPTION
**Pull request by jonas-schievink**
Closes #257

### CODE REVIEW

**Comment by Yatekii** [comment]
I don't like non-exhaustive enums personnally. Now I never have the guarantee to have handled all cases.

**Comment by jonas-schievink** [comment]
Yeah, this might not be the best way to do it. We might want to audit all error types and complete them. Maybe move DMA usage errors to a common enum.

**Comment by Yatekii** [comment]
I love the guarantees that Rust gives me with its enums, contrary to a classic Exception system, because it forces me to check all the cases. So if new features get added which require more error cases, or, even worse, a bug, I now worked around gets fixed and introduces a new error I wanna be notified about these changes, not silently burry them :)
Maybe that's just me :)

**Comment by jonas-schievink** [comment]
Yeah, closing this in favor of just auditing out error types in a future release

**Pull request closed without merging**
