### PR TITLE
Enables PWM for the nRF9160

### PR DESCRIPTION
**Pull request by huntc**
Without it, we can't have blinky on the Thingy:91 as its RGB LEDs require PWM!

This PR assumes just unsecured peripheral access for now.

I've also included a new `pwm-blinky-demo` and ensure that this and the original `pwm-demo` are included with the `xtask` tests. Additionally, the `pwm-blinky-demo` is tested for the nRF9160 target.

Tested on an nRF9160-dk via the probe-rs/embed tool. The result from `cargo embed`:

image

cc @kalkyl

### CODE REVIEW

**Comment by jonathanpallant** [comment]
Works on my nRF9160-DK. It might be worth a second PR just confirming which boards this examples are designed to run on.

**Comment by jonathanpallant** [comment]
I also hacked it to blink at varying intensity levels to check the PWM worked correctly. We should note that on an nRF9160-DK maximum duty turns the LED off, and 0 turns the LED on (they must have an inverter in there, or they switch the ground not the Vcc).

**Comment by jonas-schievink** [comment]
bors r=jonathanpallant

**Pull request merged**
